### ISSUE TITLE
Collaborative science: tools and methods

### ISSUE THREAD

**Issue by strasser** [DDD-Moore/early-career-hawaii#11]
software for collaboration
communication strategies

**Comment by raynamharris** [comment]
A resource template for setting guidelines for open source contributions 
https://opensource.com/life/16/3/contributor-guidelines-template-and-tips

**Comment by raynamharris** [comment]
Would a discussion of data sharing fall here?  I want to test my bioinformatic methods on publish data of simiiar kind (e.g. [an RNAseq database](https://elifesciences.org/elife-news/supplementary-data)). I would recreate their figures with my data and vice versa to see what patterns stand out with more data and ask how robust are the experimental methods and bioinformatic pipelines.

**Comment by strasser** [comment]
@raynamharris we could add the data sharing topic to a list of potential discussion topics for Friday. Seems like a great convo in which others might be interested. Added here: https://github.com/DDD-Moore/early-career-hawaii/issues/12

**Comment by strasser** [comment]
Closing this - not enough interest.
