### ISSUE TITLE
entrepreneurship & starting a non/for profit

### ISSUE THREAD

**Issue by strasser** [DDD-Moore/early-career-hawaii#5]
Survey comment 1: I'd attend a group on entrepreneurship and starting new orgs as a very engaged participant.

Survey comment 2: I have been an entrepreneur, so I can co-lead a discussion about entrepreneurship. It is not my current focus, so I wouldn't want to be the only lead.

**Comment by bernease** [comment]
I'm very interested in participating in this group. I'm ramping up to work on a white paper regarding entrepreneurship opportunities and case studies from researchers.

**Comment by lederman** [comment]
I led a startup in the past (survey comment 2), I will be happy to contribute to this discussion.

**Comment by strasser** [comment]
Might be a good topic for the overlap day with MMI - David Lang from OpenROV could join

**Comment by strasser** [comment]
Moving this into #10
