### ISSUE TITLE
Tools & Methods

### ISSUE THREAD

**Issue by strasser** [DDD-Moore/early-career-hawaii#6]
survey comment 1: interest in methodology (modeling, validation, detecting overfitting, etc.)

survey comment 2: I would like to give a short demo of a new collaboration tool, Code Ocean, that I have been beta-testing. It allows user to publish fully working code (with real data) that can be modified and run on the server, without local installation - a one click demo of code from papers. The website would also give me accounts for people in the symposium who are interested.

survey comment 3: My works are at the interface between optics and neuroscience. My interests are in efficient methods for online processing of big data in task-based application e.g. real-time readout of neural activity, brain machine-interfaces.

**Comment by raynamharris** [comment]
Would a discussion of data sharing fall here?  I want to test my bioinformatic methods on publish data of simliar kind. I would recreate their figures with my data and vice versa to see what patterns stand out with more data and ask how robust are the experimental methods and bioinformatic pipelines.

**Comment by strasser** [comment]
Closing this - generally people are interested in breaking up by data type - #16
